### ISSUE TITLE
Missing Export error during build

### ISSUE THREAD

**Issue by devintuffy** [headwirecom/peregrine-cms#13]
Rollup.js produces scores of this error while building the vue templates:

```
[ERROR] { Error: 'default' is not exported by ../../../buildscripts/node_modules/vue-runtime-helpers/dist/normalize-component.js
[ERROR]     at error (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:3597:30)
[ERROR]     at Module.error (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:14376:9)
[ERROR]     at handleMissingExport (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:14046:21)
[ERROR]     at Module.traceVariable (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:14477:17)
[ERROR]     at ModuleScope.findVariable (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:13811:29)
[ERROR]     at Identifier$$1.bind (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:11160:40)
[ERROR]     at CallExpression.NodeBase.bind (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:10190:23)
[ERROR]     at CallExpression.bind (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:11272:31)
[ERROR]     at ExportDefaultDeclaration$$1.NodeBase.bind (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:10190:23)
[ERROR]     at Program.NodeBase.bind (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:10186:31)
[ERROR]     at Module.bindReferences (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:14329:18)
[ERROR]     at Graph.link (/Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:17149:20)
[ERROR]     at /Users/devin/per-cms/peregrine-cms/buildscripts/node_modules/rollup/dist/rollup.js:17243:19
[ERROR]     at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR]     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
[ERROR]     at startup (internal/bootstrap/node.js:283:19)
[ERROR]   code: 'MISSING_EXPORT',
[ERROR]   url:
[ERROR]    'https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-',
[ERROR]   pos: 945,
[ERROR]   loc:
[ERROR]    { file:
[ERROR]       '/Users/devin/per-cms/peregrine-cms/samples/example-vue-site/ui.apps/src/main/content/jcr_root/apps/example/components/footer/template.vue',
[ERROR]      line: 36,
[ERROR]      column: 9 }
```

The result is that the vue app isn't bundled correctly, and pages in the admin don't work at all due to missing code.

**Comment by devintuffy** [comment]
This turned out to be caused by an update to rollup-plugin-vue. As per this commit:

https://github.com/vuejs/rollup-plugin-vue/commit/fd3dfb9a4440b13b220fb2dc535506274280fa0c

rollup-plugin-commonjs is now required to be imported when we are using rollup-plugin-vue
