### ISSUE TITLE
themeclean - breadcrumbs - onAdd - "Update with Form request to undefined failed"

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#340]
![image](https://user-images.githubusercontent.com/50131232/77590119-4dcff400-6eed-11ea-9898-43960484fc73.png)

**Comment by flx-sta** [comment]
this is a very strnage bug an i can't reproduce it 100% of the times... ill leave it for now

**Comment by reusr1** [comment]
@Felix-Puetz issue should be addressed, please verify. In order to reporoduce you need to clear the application cache and edit a page that does not contain the breadcrumb.

**Comment by flx-sta** [comment]
@reusr1 nope.. still present

Here is what I did:

- Created a new page
- inserted the "breadcrumb" component
-- no console error there 
- remove the component
- do a FULL reload (shift + control + r)
- insert breadcrumb again

![image](https://user-images.githubusercontent.com/50131232/78000078-fd64f600-7333-11ea-9d67-efa544166309.png)

**Comment by flx-sta** [comment]
It's a bit more complex.
I've inserted multiple `<breadcrumbs>` components.
couple of them worked. You get to a certain point though where it fails but its not really obvious what is causing that.

<details>
  <summary>Screenshots</summary>
  
  ![image](https://user-images.githubusercontent.com/50131232/78025088-b4279d00-7359-11ea-8c83-0e1cf38ae3c5.png)

![image](https://user-images.githubusercontent.com/50131232/78025227-f05afd80-7359-11ea-915b-a7a479917c8b.png)
</details>

<details>
  <summary>Error Log:</summary>
  
```prolog
31.03.2020 14:35:35.406 *INFO* [EventAdminThread #9] org.apache.sling.event.impl.jobs.queues.JobQueueImpl.<main queue> Starting job queue <main queue>
31.03.2020 14:35:35.407 *INFO* [EventAdminThread #9] org.apache.sling.event Service [QueueMBean for queue <main queue>,5346, [org.apache.sling.event.jobs.jmx.StatisticsMBean]] ServiceEvent REGISTERED
31.03.2020 14:35:44.210 *WARN* [0:0:0:0:0:0:0:1 [1585658144210] GET /perapi/admin/access.json HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
31.03.2020 14:35:46.881 *INFO* [0:0:0:0:0:0:0:1 [1585658146879] GET /etc/felibs/admin/main.js.map HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Resource /etc/felibs/admin/main.js.map not found
31.03.2020 14:35:51.520 *INFO* [0:0:0:0:0:0:0:1 [1585658151430] POST /perapi/admin/createSite.json HTTP/1.1] com.peregrine.admin.resource.AdminResourceHandlerService No replacements defined for resource '/content/flex01/pages'
31.03.2020 14:35:51.576 *WARN* [0:0:0:0:0:0:0:1 [1585658151575] GET /perapi/admin/access.json HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
31.03.2020 14:35:52.866 *WARN* [0:0:0:0:0:0:0:1 [1585658152866] GET /perapi/admin/access.json HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
31.03.2020 14:35:54.818 *WARN* [0:0:0:0:0:0:0:1 [1585658154817] GET /perapi/admin/access.json HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
31.03.2020 14:35:54.898 *WARN* [0:0:0:0:0:0:0:1 [1585658154897] GET /perapi/admin/readNode.json/content/flex01/pages/Sample%20Sites HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
31.03.2020 14:36:01.748 *ERROR* [0:0:0:0:0:0:0:1 [1585658161744] GET /content/flex01/pages/Sample%20Sites/jcr:content.model.json HTTP/1.1] org.apache.sling.models.impl.ExportServlet.com.peregrine.pagerender.vue.models.PageModel Could not perform export with jackson requested by model.
org.apache.sling.models.factory.ExportException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.peregrine.pagerender.vue.models.PageModel["children"]->java.util.ArrayList[0]->com.themeclean.models.BreadcrumbModel["links"])
	at org.apache.sling.models.jacksonexporter.impl.JacksonExporter.export(JacksonExporter.java:120)
	at org.apache.sling.models.impl.ModelAdapterFactory.exportModel(ModelAdapterFactory.java:1211)
	at org.apache.sling.models.impl.ExportServlet$ResourceAccessor.getExportedString(ExportServlet.java:174)
	at org.apache.sling.models.impl.ExportServlet.doGet(ExportServlet.java:94)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:270)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:346)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:378)
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552)
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
	at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:107)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:138)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151)
	at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:234)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:89)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:138)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:72)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:128)
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.peregrine.pagerender.vue.models.PageModel["children"]->java.util.ArrayList[0]->com.themeclean.models.BreadcrumbModel["links"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:343)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:698)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:704)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2493)
	at org.apache.sling.models.jacksonexporter.impl.JacksonExporter.export(JacksonExporter.java:117)
	... 55 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.peregrine.nodetypes.models.AbstractComponent.getRootResource(AbstractComponent.java:59)
	at com.themeclean.models.BreadcrumbModel.getLinks(BreadcrumbModel.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:664)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
	... 65 common frames omitted
31.03.2020 14:36:01.760 *WARN* [0:0:0:0:0:0:0:1 [1585658161759] GET /perapi/admin/readNode.json/content/flex01/pages/Sample%20Sites HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
31.03.2020 14:36:30.042 *WARN* [0:0:0:0:0:0:0:1 [1585658190042] GET /perapi/admin/access.json HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
31.03.2020 14:36:30.235 *WARN* [0:0:0:0:0:0:0:1 [1585658190234] GET /perapi/admin/access.json HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
31.03.2020 14:36:30.384 *WARN* [0:0:0:0:0:0:0:1 [1585658190384] GET /perapi/admin/access.json HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
```
</details>

**Comment by flx-sta** [comment]
1. Create a new tenant called `flex01` base on `themeclean` (i know. kinda confusing)
2. Copy the following code into the console of your browser to reproduce the error (sometimes you have to do it a couple of times):
```javascript
fetch("http://localhost:8080/content/flex01/pages/Sample%20Sites/jcr:content.model.json", {"credentials":"include","headers":{"accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.9,de;q=0.8","cache-control":"no-cache","pragma":"no-cache","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin"},"referrer":"http://localhost:8080/content/admin/pages/pages/edit.html/path:/content/flex01/pages/Sample%20Sites","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"});
```
3. investigate the problem here

**Comment by flx-sta** [comment]
@NMuzaffar 
@reggie7 
https://github.com/headwirecom/peregrine-cms/issues/340#issuecomment-606635572
Please investiage

**Comment by reggie7** [comment]
@Felix-Puetz @reusr1 - I am pretty sure it all boils down to the following stacktrace from running 
[/content/themecleanflex/pages/library/breadcrumb/jcr:content.model.json](http://localhost:8080/content/themecleanflex/pages/library/breadcrumb/jcr:content.model.json):

```08.04.2020 20:10:07.622 *ERROR* [0:0:0:0:0:0:0:1 [1586369407615] GET /content/themecleanflex/pages/library/breadcrumb/jcr:content.model.json HTTP/1.1] org.apache.sling.models.impl.ExportServlet.com.peregrine.pagerender.vue.models.PageModel Could not perform export with jackson requested by model.
org.apache.sling.models.factory.ExportException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.peregrine.pagerender.vue.models.PageModel["children"]->java.util.ArrayList[1]->com.themecleanflex.models.PagerModel["next"])
	at org.apache.sling.models.jacksonexporter.impl.JacksonExporter.export(JacksonExporter.java:120)
	at org.apache.sling.models.impl.ModelAdapterFactory.exportModel(ModelAdapterFactory.java:1211)
	at org.apache.sling.models.impl.ExportServlet$ResourceAccessor.getExportedString(ExportServlet.java:174)
	at org.apache.sling.models.impl.ExportServlet.doGet(ExportServlet.java:94)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:270)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:346)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:378)
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552)
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
	at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:107)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:138)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151)
	at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:234)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:89)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:138)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:72)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:128)
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.peregrine.pagerender.vue.models.PageModel["children"]->java.util.ArrayList[1]->com.themecleanflex.models.PagerModel["next"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:343)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:698)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:704)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2493)
	at org.apache.sling.models.jacksonexporter.impl.JacksonExporter.export(JacksonExporter.java:117)
	... 55 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.peregrine.nodetypes.models.AbstractComponent.getRootResource(AbstractComponent.java:59)
	at com.themecleanflex.models.PagerModel.getNext(PagerModel.java:622)
	at sun.reflect.GeneratedMethodAccessor419.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:664)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
	... 65 common frames omitted
```

It does not appear always, but quite frequently actually. And I'm running it on branch [issues/340](https://github.com/reggie7/peregrine-cms/tree/issues/340) that stems from `issues/93`.

**Comment by reggie7** [comment]
Fix in [PPR 363](https://github.com/headwirecom/peregrine-cms/pull/363) @Felix-Puetz @reusr1 please check.

**Comment by reusr1** [comment]
@reggie7 I was not able to reproduce this anymore after the merge :-) thank you.
