### ISSUE TITLE
avoid layout shifts by making sure we know the image width and height before rendering an image

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#460]
- annotation for sling models to support fetching image width and height
- retrofit components to consume and render the additional information

**Comment by schaefa** [comment]
I create a branch: issues/460-develop that contains the Image Info annotation and its handling as well as some Unit tests.

**Comment by reusr1** [comment]
@schaefa would you mind taking some time to migrate this feature to develop-sling12? I ran a quick test but was not able to build this change against develop-sling12 due to reflection issues

```
[main] WARN org.apache.sling.models.impl.AdapterImplementations - Unable to reflect on com.peregrine.testmodels.DefaultImageInfoModel
java.lang.NoClassDefFoundError: org/apache/commons/lang/ClassUtils
	at org.apache.sling.models.impl.ReflectionUtil.mapPrimitiveClasses(ReflectionUtil.java:112)
	at org.apache.sling.models.impl.model.ModelClassConstructor.<init>(ModelClassConstructor.java:44)
	at org.apache.sling.models.impl.model.ModelClass.getConstructors(ModelClass.java:74)
	at org.apache.sling.models.impl.model.ModelClass.updateProcessorFactories(ModelClass.java:57)
	at org.apache.sling.models.impl.model.ModelClass.<init>(ModelClass.java:49)
	at org.apache.sling.models.impl.AdapterImplementations.addAll(AdapterImplementations.java:124)
	at org.apache.sling.models.impl.AdapterImplementations.addClassesAsAdapterAndImplementation(AdapterImplementations.java:110)
	at org.apache.sling.models.impl.ModelAdapterFactorySetup.createModelAdapterFactory(ModelAdapterFactorySetup.java:23)
	at com.peregrine.model.impl.ImageInfoInjectorTest.setup(ImageInfoInjectorTest.java:48)

```

**Comment by ehdatheadwire** [comment]
@reusr1 and @reggie7 is this ticket still in progress or can it be closed? If required for 1.0.0 release, let's label it as such and make sure it's in the priority queue. Thank you!

**Comment by reggie7** [comment]
I've worked on it and fixed it, I'd say yes. @reusr1 can you confirm?

**Comment by reusr1** [comment]
@reggie7 @ehdatheadwire just tried this out, works well imho, closing the ticket
