### ISSUE TITLE
issue while creating docs site from markdown files

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#589]
Maven build fails during markdown to page conversion.

```
$ mvn clean install -PautoInstallPackage
...
[INFO] target/classes/content/docs/pages/public/distribution/index.md
[ERROR] internal/fs/utils.js:269
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: ENOENT: no such file or directory, open 'target/classes/content/docs/pages/public/distribution/index.md/../.content.xml'
[ERROR]     at Object.openSync (fs.js:462:3)
[ERROR]     at Object.writeFileSync (fs.js:1362:35)
[ERROR]     at makeContent (/home/gaston/headwire3/workspace/peregrine-cms/admin-base/ui.apps/src/main/buildjs/mdtopage.js:115:6)
[ERROR]     at /home/gaston/headwire3/workspace/peregrine-cms/admin-base/ui.apps/src/main/buildjs/mdtopage.js:135:7
[ERROR]     at Array.forEach (<anonymous>)
[ERROR]     at processDir (/home/gaston/headwire3/workspace/peregrine-cms/admin-base/ui.apps/src/main/buildjs/mdtopage.js:130:9)
[ERROR]     at /home/gaston/headwire3/workspace/peregrine-cms/admin-base/ui.apps/src/main/buildjs/mdtopage.js:133:7
[ERROR]     at Array.forEach (<anonymous>)
[ERROR]     at processDir (/home/gaston/headwire3/workspace/peregrine-cms/admin-base/ui.apps/src/main/buildjs/mdtopage.js:130:9)
[ERROR]     at Object.<anonymous> (/home/gaston/headwire3/workspace/peregrine-cms/admin-base/ui.apps/src/main/buildjs/mdtopage.js:142:1) {
[ERROR]   errno: -2,
[ERROR]   syscall: 'open',
[ERROR]   code: 'ENOENT',
[ERROR]   path: 'target/classes/content/docs/pages/public/distribution/index.md/../.content.xml'
[ERROR] }
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! pcms-admin-base@1.0.0 build: `node ./node_modules/rollup/bin/rollup -c --silent && node ../../buildscripts/buildvue.js admin && node ../../buildscripts/copyfelibs.js && node src/main/buildjs/mdtopage.js`
[ERROR] npm ERR! Exit status 1
...
```

**Comment by reusr1** [comment]
https://github.com/headwirecom/peregrine-cms/commit/25be373e5839b32835ae8141d1ac39e834333fc2

**Comment by GastonGonzalez** [comment]
Confirmed that the build succeeds and that the docs site is properly generated in Peregrine: http://localhost:8080/content/admin/pages/pages/edit.html/path:/content/docs/pages/public
