### ISSUE TITLE
Startup exception in Sling12

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#604]
When Peregrine is started with Sling12, using the `develp-sling12` branch, the following exception is thrown.

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.felix.scr.impl.inject.internal.ComponentConstructorImpl.newInstance(ComponentConstructorImpl.java:312)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:279)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:984)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:957)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:902)
	at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:348)
	at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:248)
	at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:350)
	at org.apache.felix.framework.Felix.getService(Felix.java:3954)
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:450)
	at org.apache.felix.inventory.impl.webconsole.WebConsoleAdapter.addingService(WebConsoleAdapter.java:152)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
	at org.apache.felix.inventory.impl.webconsole.WebConsoleAdapter.<init>(WebConsoleAdapter.java:68)
	at org.apache.felix.inventory.impl.Activator.start(Activator.java:63)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: No bundle context property 'sling.properties.url' provided
	at org.apache.sling.settings.impl.SlingPropertiesPrinter.<init>(SlingPropertiesPrinter.java:64)
	... 30 more
```

**Steps to Reproduce**
Start Sling using the Feature Archive. 

**NOTE: Adjust the paths accordingly**
```
java -jar org.apache.sling.feature.launcher.jar \
  -D sling.runmodes=notshared,oak_tar_fds \
  -f com.peregrine-cms.sling.launchpad-12-SNAPSHOT-oak_tar_fds_far.far \
  -p ~/opt/sling12 \
  -c ~/opt/sling12/launcher/cache
```

**Resolution**
This is a Sling issue which has been resolved with [SLING-9648](https://issues.apache.org/jira/browse/SLING-9648). 

The current FAR for Peregrine  is using _Apache Sling Settings_ version 1.4.0. It needs to be upgraded to 1.4.2.

**Comment by reusr1** [comment]
closing as this issue is solved by using the launcher/far from https://github.com/peregrine-cms/peregrine-builder
