### ISSUE TITLE
Repoinit ACL's need restart

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#677]
This test procedure uses the latest Sling Starter to illustrate the concerns happens either with Peregrine's sling12 builder or the latest Sling Starter.

1. build latest sling starter (https://github.com/apache/sling-org-apache-sling-starter.git)
    1. mvn clean install
2. Prepare Sling instance directory
    1. mv ./org.apache.sling.feature.launcher.jar to working directory
    2. mv ./feature-oak_tar.json to working dircetory
    3. mkdir sling in working directory
3. Launch Sling Starter
    1. java -jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=30303 ./org.apache.sling.feature.launcher.jar -f ./feature-oak_tar.json -D sling.runmodes=oak_tar -D org.osgi.service.http.port=8080 -p sling
4. Add missing bundles
    1. https://repo1.maven.org/maven2/org/apache/sling/org.apache.sling.distribution.api/0.3.0/org.apache.sling.distribution.api-0.3.0.jar
    2. https://repo1.maven.org/maven2/org/apache/sling/org.apache.sling.distribution.core/0.3.4/org.apache.sling.distribution.core-0.3.4.jar
5. build latest peregrine-css [develop-sling12]
    1. mvn clean install -PautoInstallPackage
6. Peregrine CMS Repoinit Checklist 
            [x]Confirm Repoinit config exists: 
                        /system/console/configMgr  org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine 
            [x] Confirm Paths
                create path (sling:Folder) /apps
                create path (sling:Folder) /content
                create path (sling:Folder) /etc
                create path (sling:Folder) /etc/felibs
                create path (sling:Folder) /etc/packages
                create path (sling:Folder) /var/recyclebin
                create path (sling:Folder) /var/sitemaps
            [x]Peregrine Service Users
                create service user peregrine-service-user
                create service user nodejs-service-user
                create service user sitemaps-cache
                create service user distribution-agent-user
                create service user defaultAgentService
            []ACL for felibs [missing]
                set ACL for everyone
                    allow jcr:read on /etc/felibs
                end
            []ACL for peregrine-service-user [missing]
               set ACL for peregrine-service-user
                    allow jcr:all on /apps
                    allow jcr:all on /content
                    allow jcr:all on /etc/felibs
                    allow jcr:all on /etc/packages
                    allow jcr:all on /home
                    allow jcr:all on /var/audit/jobs
                    allow jcr:all on /var/recyclebin
                end
            []ACL for distribution user [missing]
                set ACL for distribution-agent-user, defaultAgentService
                    allow jcr:all on /content
                    allow jcr:all on /etc/distribution
                    allow jcr:all on /libs/sling/distribution
                    allow jcr:all on /var/sling/distribution
                end
            []ACL for distribution-agent-user [missing]
                set ACL for distribution-agent-user
                    allow jcr:read on /
                end
            []ACL for Sitemap [missing]
                set ACL for sitemaps-cache
                    allow jcr:all on /var/sitemaps
                    allow jcr:read on /content
                end
            []ACL’s for all_tenants [missing]
                set ACL for all_tenants
                    allow jcr:read on /index.html
                    allow jcr:read on /favicon.ico
                    allow jcr:read on /robots.txt
                    allow jcr:read on /perapi/admin
                    allow jcr:read on /apps
                    allow jcr:read on /i18n
                    allow jcr:read on /content
                end
            [x]Create group all_tenants
                create group all_tenants with path /home/groups/tenants

**Comment by cmrockwell** [comment]
The issue with repoinit and ACL’s is not due to Sling Starter bugs. It’s the errors when Repoinit is trying to set ACL’s for paths that don’t exist yet. That’s why second attempt or restart works.

We have examples like this one, where it is trying to set ACL for index.html. This path is installed by `admin-base/ui.apps`

08.12.2020 14:37:27.549 *ERROR* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.oak.server.internal.OakSlingRepositoryManager Exception in a SlingRepositoryInitializer: RepositoryInitializerFactory, references=[], scripts=1
java.lang.RuntimeException: Failed to set ACL (javax.jcr.PathNotFoundException: Cannot set ACL on non-existent path /index.html) AclLine ALLOW {paths=[/index.html], privileges=[jcr:read]}
    at org.apache.sling.jcr.repoinit.impl.AclVisitor.setAcl(AclVisitor.java:64) [org.apache.sling.jcr.repoinit:1.1.26]
    at org.apache.sling.jcr.repoinit.impl.AclVisitor.visitSetAclPrincipal(AclVisitor.java:85) [
...
Caused by: javax.jcr.PathNotFoundException: Cannot set ACL on non-existent path /index.html
    at org.apache.sling.jcr.repoinit.impl.AclUtil.setAcl(AclUtil.java:120) [org.apache.sling.jcr.repoinit:1.1.26]
    at org.apache.sling.jcr.repoinit.impl.AclVisitor.setAcl(AclVisitor.java:62) [org.apache.sling.jcr.repoinit:1.1.26]
    ... 32 common frames omitted
