### ISSUE TITLE
permissions not set up correctly after the first launch of peregrine sling12 variation

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#735]
when running 

`java -jar org.apache.sling.feature.launcher.jar -f com.peregrine-cms.sling.launchpad-12-SNAPSHOT-oak_tar_far.far -p sling`

the first time and installing peregrine on top of this blank sling instance the permissions are not set up correctly based on the peregrine repoinit script

The permissions are correct after stopping and starting the sling instance

**Comment by reggie7** [comment]
Hint: when saving [`org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine`](http://localhost:8080/system/console/configMgr/org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine) [config](https://github.com/headwirecom/peregrine-cms/blob/develop-sling12/platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-peregrine.config) we get the following inside `error.log`:
```
10.02.2021 15:07:57.448 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.RepositoryInitializerFactory Executing 19 repoinit operations
10.02.2021 15:07:57.449 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.UserVisitor Service user peregrine-service-user already exists, no changes made.
10.02.2021 15:07:57.449 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.UserVisitor Service user nodejs-service-user already exists, no changes made.
10.02.2021 15:07:57.449 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.UserVisitor Service user sitemaps-cache already exists, no changes made.
10.02.2021 15:07:57.449 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.UserVisitor Service user distribution-agent-user already exists, no changes made.
10.02.2021 15:07:57.449 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.UserVisitor Service user defaultAgentService already exists, no changes made.
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.UserVisitor Group all_tenants already exists, no changes made
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /apps
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /content
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /etc
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /etc
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /etc/felibs
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /etc
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /etc/packages
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /var
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /var/recyclebin
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /var
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Path already exists, nothing to do (and not checking its primary type for now): /var/sitemaps
10.02.2021 15:07:57.450 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [everyone] on [/etc/felibs]
10.02.2021 15:07:57.451 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [peregrine-service-user] on [/apps]
10.02.2021 15:07:57.452 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [peregrine-service-user] on [/content]
10.02.2021 15:07:57.453 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [peregrine-service-user] on [/etc/felibs]
10.02.2021 15:07:57.454 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [peregrine-service-user] on [/etc/packages]
10.02.2021 15:07:57.454 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [peregrine-service-user] on [/home]
10.02.2021 15:07:57.455 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [peregrine-service-user] on [/var/audit/jobs]
10.02.2021 15:07:57.456 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [peregrine-service-user] on [/var/recyclebin]
10.02.2021 15:07:57.456 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [distribution-agent-user, defaultAgentService] on [/content]
10.02.2021 15:07:57.457 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [distribution-agent-user, defaultAgentService] on [/etc/distribution]
10.02.2021 15:07:57.458 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [distribution-agent-user, defaultAgentService] on [/libs/sling/distribution]
10.02.2021 15:07:57.459 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [distribution-agent-user, defaultAgentService] on [/var/sling/distribution]
10.02.2021 15:07:57.459 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [distribution-agent-user] on [/]
10.02.2021 15:07:57.461 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:all]' for [sitemaps-cache] on [/var/sitemaps]
10.02.2021 15:07:57.462 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [sitemaps-cache] on [/content]
10.02.2021 15:07:57.463 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [all_tenants] on [/index.html]
10.02.2021 15:07:57.464 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [all_tenants] on [/favicon.ico]
10.02.2021 15:07:57.464 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [all_tenants] on [/robots.txt]
10.02.2021 15:07:57.465 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [all_tenants] on [/perapi]
10.02.2021 15:07:57.465 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [all_tenants] on [/apps]
10.02.2021 15:07:57.467 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [all_tenants] on [/i18n]
10.02.2021 15:07:57.467 *INFO* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine)] org.apache.sling.jcr.repoinit.impl.AclVisitor Adding ACL 'allow' entry '[jcr:read]' for [all_tenants] on [/content]
10.02.2021 15:07:57.479 *ERROR* [OsgiInstallerImpl] org.apache.sling.installer.provider.jcr.impl.JcrInstaller Unable to add/update resource config:org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine
javax.jcr.AccessDeniedException: Access denied.
	at org.apache.jackrabbit.oak.jcr.security.AccessManager.checkPermissions(AccessManager.java:71) [org.apache.jackrabbit.oak-jcr:1.32.0]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:311) [org.apache.jackrabbit.oak-jcr:1.32.0]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:280) [org.apache.jackrabbit.oak-jcr:1.32.0]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:207) [org.apache.jackrabbit.oak-jcr:1.32.0]
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:112) [org.apache.jackrabbit.oak-jcr:1.32.0]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.addNode(NodeImpl.java:280) [org.apache.jackrabbit.oak-jcr:1.32.0]
	at org.apache.sling.installer.provider.jcr.impl.JcrUtil.createPath(JcrUtil.java:70) [org.apache.sling.installer.provider.jcr:3.3.0]
	at org.apache.sling.installer.provider.jcr.impl.JcrInstaller.handleUpdate(JcrInstaller.java:702) [org.apache.sling.installer.provider.jcr:3.3.0]
	at org.apache.sling.installer.provider.jcr.impl.JcrInstaller.handleUpdate(JcrInstaller.java:596) [org.apache.sling.installer.provider.jcr:3.3.0]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.internalResourceAddedOrUpdated(OsgiInstallerImpl.java:1198) [org.apache.sling.installer.core:3.11.2]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.processUpdateInfos(OsgiInstallerImpl.java:1116) [org.apache.sling.installer.core:3.11.2]
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:280) [org.apache.sling.installer.core:3.11.2]
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by reggie7** [comment]
#736 on the way, so closing it here.

**Comment by reusr1** [comment]
@reggie7 lets close tickets once the PR is verified and merged, right?

**Comment by reusr1** [comment]
verified, permissions are set up correctly when peregrine is launched the first time
